Add PR URL to output
launchdarkly-labs/pr-downstream pull request #8
Opened 2024-11-14 10:07 UTC by hoshsadiq

2024-11-18 15:23 UTC, ldhenry requested changes

2024-11-18 15:23 UTC, ldhenry commented on action.yml
> +      if: ${{ steps.cpr.outputs.pull-request-number }}
I think this might make more sense, right?
```suggestion
      if: ${{ steps.create-pr.outputs.pull-request-url }}
```

2024-11-19 12:21 UTC, hoshsadiq commented on action.yml
> +      if: ${{ steps.cpr.outputs.pull-request-number }}
Weird! Could have sworn I had made that change :man_shrugging: Thanks! Fixed!

2024-11-27 15:58 UTC, ldhenry approved these changes
LGTM

2024-11-27 15:58 UTC, merged